### ISSUE TITLE
Segmentation fault (Core dumped) when running test.py

### ISSUE THREAD

**Issue by lizabelos** [t-vi/warp-ctc#5]
Hi,

Running test.py with Python 3.6.5 and PyTorch 0.4.0 cause a segmentation fault.

**Comment by t-vi** [comment]
Thank you for your bug report.
Usually this is a sign of compiler version (ABI?) mismatches.
- Do you use pre-built PyTorch binaries or self-compile?
- What GCC version do you use to compile warp-ctc? Are you sure they are compatible?

**Comment by lizabelos** [comment]
- I use the pre-built PyTorch binaries
- gcc (Ubuntu 4.8.5-2ubuntu1~14.04.1) 4.8.5

**Comment by t-vi** [comment]
Could you retry using gcc 5, please? Or, if you can, rebuild both PyTorch and warp-ctc with the same compiler.

**Comment by lizabelos** [comment]
It's working with GCC 5.

**Comment by t-vi** [comment]
Thanks for reporting back! I have added a **bold** warning to the README.md.
